### ISSUE TITLE
Оновлення Схеми Бази Даних

### ISSUE THREAD

**Issue by pasteliak0414** [pasteliak0414/DutyMaster#10]
Оновити схему для Бази Даних, відповідно до нового функціоналу коду.

**Comment by drndchnk** [comment]
Схему для Бази Даних оновлено!
![photo_2023-07-23_22-28-34](https://github.com/pasteliak0414/DutyMaster/assets/128164416/6de9cd83-d861-44a8-b9ce-fe7e79e6b4dc)
