### ISSUE TITLE
Випуск версії

### ISSUE THREAD

**Issue by pasteliak0414** [pasteliak0414/DutyMaster#13]
Доповісти про готовність усіх елементів проєкту.

**Comment by Hulumulu258** [comment]
Код програми до випуску бета-версії готовий.

**Comment by drndchnk** [comment]
База Даних перевірена та оновлена, все готове до використання.

**Comment by Vazhiyy** [comment]
Свою частину роботи виконала. Всі тести пройдено. Програма працює належним чином.

**Comment by Artem3216** [comment]
Всі вимоги було дотримано, додана нова функція, чекаю на перевірку шляхом тестування

**Comment by Artem3216** [comment]
Свою частину роботи завершив, програма готова до використання

**Comment by pasteliak0414** [comment]
Всім дякую за співпрацю! Готуємося до презентації проєкту.
