### ISSUE TITLE
План проекту

### ISSUE THREAD

**Issue by pasteliak0414** [pasteliak0414/DutyMaster#5]
Вітання! Починаємо роботу над "DutyMaster". Чекаю від розробника тестовий приклад коду з урахуванням вимог, вимоги додаю у файлі. За результатами чекаю від одного розробника звітність.

**Comment by Artem3216** [comment]
Виконано! Тестова програма надіслана на електронну пошту.

**Comment by Hulumulu258** [comment]
Код змінено до вимог.
