### ISSUE TITLE
Схема Бази Даних

### ISSUE THREAD

**Issue by pasteliak0414** [pasteliak0414/DutyMaster#8]
Чекаю від системного аналітика схему до бази даних, яку необхідно виконати у відповідності до коду програми.

**Comment by drndchnk** [comment]
Попередня схема буде виглядати наступним чином
![photo_2023-07-23_13-30-43](https://github.com/pasteliak0414/DutyMaster/assets/128164416/a154b08d-ab93-42ef-acfe-36cc55a69e5a)
